Update redux dependency
civicsource/redux-rsi pull request #13
Opened 2018-04-06 21:28 UTC by cdakin1

Updates redux dependency to beta version. This is necessary for react-redux to support lifecycle methods introduced in react 16.3 [[Link](https://github.com/reactjs/react-redux/issues/915)]

Note: As soon as redux releases a stable v4.0 we'll want to update again, and for now release this is a beta version.

2018-04-06 21:32 UTC, mdarens submitted a review, later dismissed

2018-04-09 16:41 UTC, chadly requested changes

2018-04-09 16:41 UTC, chadly commented on package.json
> +    "redux": "4.0.0-beta.2"
Can we just do `>= 3.x <= 4` here? Will that allow consuming clients to pull in `4.0.0-beta.2`? I would think so.

2018-04-10 21:32 UTC, chadly approved these changes

2018-04-10 21:33 UTC, merged

2018-04-10 21:36 UTC, chadly commented
Published as [`v4.0.1`](https://github.com/civicsource/redux-rsi/releases/tag/v4.0.1)